name: "02: Deploy to Staging"

on:
  push:
    branches:
      - release/*
      - hotfix/*

jobs:
  simulate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch 🌿
        run: echo "Branch is ${{ github.ref_name }}"
      - name: Deploy
        run: echo "Deploy to staging (simulated) 🚀"
